### ISSUE TITLE
Username or Password is invalid

### ISSUE THREAD

**Issue by ajscodes** [ajscodes/Real-World-Tools#2]
If username is true then it check password is correct or not but if username is not correct and password is correct i get username or password is incorrect. I want perfect what's exactly wrong username or password if username is incorrect.

**Comment by DevanshGanatra** [comment]
if(enteredUsername.equals(correctUsername)){
            if(enteredPassward.equals(correctPassward)){
                System.out.print("Successfully Login");
            }
            else{
                System.out.print("Incorrect Passward!");
            }
        }
        else{
            if(enteredPassword.equals(correctPassword){
            System.out.print("Incorrect Username!");
            }
           else{
            System.out.print("Incorrect Username and Password!"); 
            }
        }

//this will make your code as per your need .
